#PATHS

RAW_DATA_DIR : 'data/raw/'
PROC_DATA_DIR : 'data/processed/'
INTERIM_DATA_DIR : 'data/interim/'
MODEL_SAVE_DIR : 'models_/'
VIS_PREDS_DIR : 'data/vis/'
CMP_FMT : '.tar.bz2'
RUNS_DIR : 'runs/'


PODS_DIR : 'data/raw/pods'
PODS_TRAIN_DIR : 'data/interim/pods_train'
PODS_VAL_DIR : 'data/interim/pods_val'
PODS_TEST_DIR : 'data/interim/pods_test'
PODS_DATA_INFO : 'data/tagged_podcasts.json'

ADS_DIR : 'data/raw/ads'
NON_ADS_DIR : 'data/raw/non_ads'
ADS_VIS_DIR : 'data/vis/ads'
TRANSCRIPTS_VIS_DIR : 'data/vis/transcripts'

PODS_READ_FORMAT_PODS : '.mp3'
AUDIO_READ_FORMAT_PODS : '.wav'
AUDIO_WRITE_FORMAT_PODS : '.wav'

AUDIO_READ_FORMAT_TIMIT : '.WAV'
AUDIO_WRITE_FORMAT : '.wav'


TIMIT_DATA_PACKED : 'data/raw/TIMIT.zip'
TIMIT_DATA_INFO : 'data/raw/TIMIT/README.DOC'
TIMIT_DATA_TRAIN : 'data/raw/timit/data/TRAIN'
TIMIT_DATA_TEST : 'data/raw/timit/data/TEST'
VAD_MODE_DIARIZATION : 3
WINDOW_SIZE_DIARIZATION : 25 #ms
WINDOW_STEP_DIARIZATION : 10 #ms
SLIDING_WIN_SIZE_DIARAIZATION : 64 # frames

VAD_MODE_SUPERVISED : 2
WINDOW_SIZE_SUPERVISED : 48 #ms
WINDOW_STEP_SUPERVISED : 12 #ms
SLIDING_WIN_SIZE_SUPERVISED : 301


SAMPLING_RATE : 16000 #Hz
MEL_CHANNELS : 40
SMOOTHING_WSIZE : 10
SMOOTHING_LENGTH : 3
DBFS : -30
HIDDEN_SIZE : 256 
EMBEDDING_SIZE : 256
PROJECTION_SIZE : 64
NUM_LAYERS : 3
SLIDING_WIN_OVERLAP : 0.5
BATCH_SIZE : 64
VAL_LOSS_COUNT : 100


WINDOW_SIZE: 25
WINDOW_STEP: 10
VAD_MODE: 3
ACC_COUNT: 4
SLIDING_WIN_SIZE : 64 # frames
UTTR_COUNT : 5
BATCH_SIZE_DIARAIZATION : 20

